// Define the SalaryRecord interface
interface SalaryRecord {
  employeeId: string;
  name: string;
  email: string;
  paymentDate: string;
  yearMonth: string;
  baseSalary: number;
  bonus: number;
  unpaidLeaves: number;
  deductions: number;
  totalAmount: number;
  receiverAddress: string;
  image: string;
}

export const salaryData: SalaryRecord[] = [
    {
      employeeId: "EMP001",
      name: "John Doe",
      email: "john.doe@example.com",
      paymentDate: "Jan 31, 2024",
      yearMonth: "2024/01",
      baseSalary: 3500,
      bonus: 100,
      unpaidLeaves: 2,
      deductions: 140,
      totalAmount: 3460,
      receiverAddress: "Xcff...cd412",
      image: "/images/image.png"
    },
    {
      employeeId: "EMP002",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      paymentDate: "Dec 31, 2023",
      yearMonth: "2023/12",
      baseSalary: 3300,
      bonus: 200,
      unpaidLeaves: 1,
      deductions: 70,
      totalAmount: 3430,
      receiverAddress: "Xcff...cd412",
      image: "/images/image(1).png"
    },
    {
      employeeId: "EMP003",
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      paymentDate: "Jan 31, 2024",
      yearMonth: "2023/12",
      baseSalary: 3200,
      bonus: 50,
      unpaidLeaves: 0,
      deductions: 0,
      totalAmount: 3250,
      receiverAddress: "Xcff...cd412",
      image: "/images/image.png"
    },
    {
      employeeId: "EMP004",
      name: "Bob Brown",
      email: "bob.brown@example.com",
      paymentDate: "Jan 31, 2024",
      yearMonth: "2023/12",
      baseSalary: 3500,
      bonus: 400,
      unpaidLeaves: 0,
      deductions: 0,
      totalAmount: 3900,
      receiverAddress: "Xcff...cd412",
      image: "/images/image(1).png"
    },
    {
      employeeId: "EMP005",
      name: "Charlie Green",
      email: "charlie.green@example.com",
      paymentDate: "Jan 31, 2024",
      yearMonth: "2023/12",
      baseSalary: 3500,
      bonus: 200,
      unpaidLeaves: 0,
      deductions: 0,
      totalAmount: 3700,
      receiverAddress: "Xcff...cd412",
      image: "/images/image.png"
    },
    {
        employeeId: "EMP001",
        name: "John Doe",
        email: "john.doe@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3500,
        bonus: 100,
        unpaidLeaves: 2,
        deductions: 140,
        totalAmount: 3460,
        receiverAddress: "Xcff...cd412",
        image: "/images/image.png"
      },
      {
        employeeId: "EMP002",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        paymentDate: "Dec 31, 2023",
        yearMonth: "2023/12",
        baseSalary: 3300,
        bonus: 200,
        unpaidLeaves: 1,
        deductions: 70,
        totalAmount: 3430,
        receiverAddress: "Xcff...cd412",
        image: "/images/image(1).png"
      },
      {
        employeeId: "EMP003",
        name: "Alice Johnson",
        email: "alice.johnson@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2023/12",
        baseSalary: 3200,
        bonus: 50,
        unpaidLeaves: 0,
        deductions: 0,
        totalAmount: 3250,
        receiverAddress: "Xcff...cd412",
        image: "/images/image.png"
      },
      {
        employeeId: "EMP004",
        name: "Bob Brown",
        email: "bob.brown@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2023/12",
        baseSalary: 3500,
        bonus: 400,
        unpaidLeaves: 0,
        deductions: 0,
        totalAmount: 3900,
        receiverAddress: "Xcff...cd412",
        image: "/images/image(1).png"
      },
      {
        employeeId: "EMP005",
        name: "Charlie Green",
        email: "charlie.green@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2023/12",
        baseSalary: 3500,
        bonus: 200,
        unpaidLeaves: 0,
        deductions: 0,
        totalAmount: 3700,
        receiverAddress: "Xcff...cd412",
        image: "/images/image.png"
      },
      {
        employeeId: "EMP006",
        name: "David White",
        email: "david.white@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3100,
        bonus: 150,
        unpaidLeaves: 1,
        deductions: 50,
        totalAmount: 3200,
        receiverAddress: "Xcff...cd412",
        image: "/images/image(1).png"
      },
      {
        employeeId: "EMP007",
        name: "Emma Wilson",
        email: "emma.wilson@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3400,
        bonus: 250,
        unpaidLeaves: 0,
        deductions: 80,
        totalAmount: 3570,
        receiverAddress: "Xcff...cd412",
        image: "/images/image.png"
      },
      {
        employeeId: "EMP008",
        name: "Frank Thomas",
        email: "frank.thomas@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3600,
        bonus: 300,
        unpaidLeaves: 1,
        deductions: 90,
        totalAmount: 3810,
        receiverAddress: "Xcff...cd412",
        image: "/images/image(1).png"
      },
      {
        employeeId: "EMP009",
        name: "Grace Hall",
        email: "grace.hall@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3200,
        bonus: 120,
        unpaidLeaves: 2,
        deductions: 60,
        totalAmount: 3260,
        receiverAddress: "Xcff...cd412",
        image: "/images/image.png"
      },
      {
        employeeId: "EMP010",
        name: "Henry Scott",
        email: "henry.scott@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3700,
        bonus: 350,
        unpaidLeaves: 0,
        deductions: 100,
        totalAmount: 3950,
        receiverAddress: "Xcff...cd412",
        image: "/images/image(1).png"
      },
      {
        employeeId: "EMP001",
        name: "John Doe",
        email: "john.doe@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3500,
        bonus: 100,
        unpaidLeaves: 2,
        deductions: 140,
        totalAmount: 3460,
        receiverAddress: "Xcff...cd412",
        image: "/images/image.png"
      },
      {
        employeeId: "EMP002",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        paymentDate: "Dec 31, 2023",
        yearMonth: "2023/12",
        baseSalary: 3300,
        bonus: 200,
        unpaidLeaves: 1,
        deductions: 70,
        totalAmount: 3430,
        receiverAddress: "Xcff...cd412",
        image: "/images/image(1).png"
      },
      {
        employeeId: "EMP003",
        name: "Alice Johnson",
        email: "alice.johnson@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2023/12",
        baseSalary: 3200,
        bonus: 50,
        unpaidLeaves: 0,
        deductions: 0,
        totalAmount: 3250,
        receiverAddress: "Xcff...cd412",
        image: "/images/image.png"
      },
      {
        employeeId: "EMP004",
        name: "Bob Brown",
        email: "bob.brown@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2023/12",
        baseSalary: 3500,
        bonus: 400,
        unpaidLeaves: 0,
        deductions: 0,
        totalAmount: 3900,
        receiverAddress: "Xcff...cd412",
        image: "/images/image(1).png"
      },
      {
        employeeId: "EMP005",
        name: "Charlie Green",
        email: "charlie.green@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2023/12",
        baseSalary: 3500,
        bonus: 200,
        unpaidLeaves: 0,
        deductions: 0,
        totalAmount: 3700,
        receiverAddress: "Xcff...cd412",
        image: "/images/image.png"
      },
      {
        employeeId: "EMP006",
        name: "David White",
        email: "david.white@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3100,
        bonus: 150,
        unpaidLeaves: 1,
        deductions: 50,
        totalAmount: 3200,
        receiverAddress: "Xcff...cd412",
        image: "/images/image(1).png"
      },
      {
        employeeId: "EMP007",
        name: "Emma Wilson",
        email: "emma.wilson@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3400,
        bonus: 250,
        unpaidLeaves: 0,
        deductions: 80,
        totalAmount: 3570,
        receiverAddress: "Xcff...cd412",
        image: "/images/image.png"
      },
      {
        employeeId: "EMP008",
        name: "Frank Thomas",
        email: "frank.thomas@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3600,
        bonus: 300,
        unpaidLeaves: 1,
        deductions: 90,
        totalAmount: 3810,
        receiverAddress: "Xcff...cd412",
        image: "/images/image(1).png"
      },
      {
        employeeId: "EMP009",
        name: "Grace Hall",
        email: "grace.hall@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3200,
        bonus: 120,
        unpaidLeaves: 2,
        deductions: 60,
        totalAmount: 3260,
        receiverAddress: "Xcff...cd412",
        image: "/images/image.png"
      },
      {
        employeeId: "EMP010",
        name: "Henry Scott",
        email: "henry.scott@example.com",
        paymentDate: "Jan 31, 2024",
        yearMonth: "2024/01",
        baseSalary: 3700,
        bonus: 350,
        unpaidLeaves: 0,
        deductions: 100,
        totalAmount: 3950,
        receiverAddress: "Xcff...cd412",
        image: "/images/image(1).png"
      },
  ];